config/routes.rb
Sophi::Application.routes.draw do
  resources :assignments

  namespace :my do
    resources :home
  end
  get "my/home"

  devise_for :users

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/activity.rb
class Activity
  include Mongoid::Document
  field :object_type, type: String
  field :uri, type: String
  field :definition, type: String
  belongs_to :statement
end

app/models/activity_definition.rb
class ActivityDefinition
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :type, type: String
  field :interaction_type, type: String
  field :extensions, type: String
end

app/models/agent.rb
class Agent
  include Mongoid::Document
  field :object_type, type: String
  field :name, type: String
  field :mbox, type: String
  field :mbox_sha1sum, type: String
  field :openid, type: String
  field :account, type: String
  belongs_to :statement
end

app/models/assignment.rb
class Assignment
  include Mongoid::Document
  field :title, type: String
  field :body, type: String
  field :due, type: Time
end

app/models/authority.rb
class Authority
  include Mongoid::Document
  field :object_type, type: String
  field :member
  embedded_in :statement
end

app/models/context.rb
class Context
  include Mongoid::Document
  field :registration, type: String
  field :instructor, type: String
  field :team, type: String
  field :contextActivities, type: String
  field :revision, type: String
  field :platform, type: String
  field :language, type: String
  field :statement, type: String
  field :extensions, type: String
end

app/models/group.rb
class Group < Agent
  include Mongoid::Document
  embeds_many :agents, store_as: :members
end

app/models/hoge.rb
class Hoge
  include Mongoid::Document
end

app/models/result.rb
class Result
  include Mongoid::Document
  embeds_one :score
  field :success, type: String
  field :completioon, type: String
  field :response, type: String
  field :duration, type: String
  field :extensions, type: String
end

app/models/score.rb
class Score
  include Mongoid::Document
  field :scaled, type: String
  field :raw, type: String
  field :min, type: String
  field :max, type: String
  embedded_in :result
end

app/models/statement.rb
class Statement
  include Mongoid::Document
  has_many :user #actor
  embeds_one :verb
  
  #object subclass 
  has_one :activity
  has_one :agent
  has_one :statement #statement_ref

  embeds_one :result
  embeds_one :authority

  field :context, type: String
  field :timestamp, type: String
  field :stored, type: String
  field :voided, type: String

  #belonging
  belongs_to :statement
end

app/models/statement_ref.rb
class StatementRef
  include Mongoid::Document
  field :objectType 
  field :id
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Admin?
  field :admin

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  validates_presence_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String

  # LRS Attributes
  field :objectType
  field :email, as: :mbox

  belongs_to :statement
end

app/models/verb.rb
class Verb
  include Mongoid::Document
  field :uri, type: String
  field :display, type: Hash

  embedded_in :statement
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assignments }
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/new
  # GET /assignments/new.json
  def new
    @assignment = Assignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/1/edit
  def edit
    @assignment = Assignment.find(params[:id])
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(params[:assignment])

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render json: @assignment, status: :created, location: @assignment }
      else
        format.html { render action: "new" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assignments/1
  # PUT /assignments/1.json
  def update
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      if @assignment.update_attributes(params[:assignment])
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/my/home_controller.rb
class My::HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    add_crumb I18n.t('label.home'), my_home_index_path
    @assignments=Assignment.all
    @user=User.first
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to my_home_index_path
    else
      add_crumb I18n.t('label.top'), '/'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/my/home_helper.rb
module My::HomeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/assignments/_form.html.haml
= form_for @assignment do |f|
  - if @assignment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@assignment.errors.count, "error")} prohibited this assignment from being saved:"
      %ul
        - @assignment.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_field :body
  .field
    = f.label :due
    = f.datetime_select :due
  .actions
    = f.submit 'Save'

app/views/assignments/edit.html.haml
%h1 Editing assignment

= render 'form'

= link_to 'Show', @assignment
\|
= link_to 'Back', assignments_path

app/views/assignments/index.html.haml
%h1 Listing assignments

%table
  %tr
    %th Title
    %th Body
    %th Due
    %th
    %th
    %th

  - @assignments.each do |assignment|
    %tr
      %td= assignment.title
      %td= assignment.body
      %td= assignment.due
      %td= link_to 'Show', assignment
      %td= link_to 'Edit', edit_assignment_path(assignment)
      %td= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Assignment', new_assignment_path

app/views/assignments/new.html.haml
%h1 New assignment

= render 'form'

= link_to 'Back', assignments_path

app/views/assignments/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @assignment.title
%p
  %b Body:
  = @assignment.body
%p
  %b Due:
  = @assignment.due

= link_to 'Edit', edit_assignment_path(@assignment)
\|
= link_to 'Back', assignments_path

app/views/my/home/index.html.haml
%h1= t 'label.todo'
%p XXXXXXXXXXXXXXXXXXX
%p XXXXXXXXXXXXXXXXXXX
%p XXXXXXXXXXXXXXXXXXX

%h1=t 'label.assignment'
%assignments{:data=>{:assignments=>"#{@assignments.to_json}"}}
  -@assignments.each do|assignment|
    %p=assignment.name
%p XXXXXXXXXXXXXXXXXXX
%p XXXXXXXXXXXXXXXXXXX
%p XXXXXXXXXXXXXXXXXXX
%h1=t 'label.log'
%p XXXXXXXXXXXXXXXXXXX
%p XXXXXXXXXXXXXXXXXXX
%p XXXXXXXXXXXXXXXXXXX

app/views/welcome/index.html.haml
%h1 Timeline
- 10.times.each do
  %div.row
    %div.span1
      =gravatar_image_tag('hgsk85@gmail.com', :alt=>"hoge")
    %div.span1 hogehoge